<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-04-20T06:06:28+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'timezone' => 'Asia/Kuala_Lumpur',
);
