<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-04-06T16:09:57+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      background_image
 * @group     login_page_background
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'background_image' => '3',
);
