<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-08-18T12:42:10+08:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      cartOverlay
 * @group     vividstore
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'productPublishTarget' => '250',
    'symbol' => 'RM ',
    'whole' => '.',
    'thousand' => ',',
    'sizeUnit' => 'in',
    'weightUnit' => 'lb',
    'taxName' => 'Tax',
    'cartOverlay' => false,
    'taxenabled' => null,
    'taxcountry' => null,
    'taxstate' => null,
    'taxcity' => '',
    'taxAddress' => '',
    'taxMatch' => '',
    'taxBased' => '',
    'taxrate' => '',
    'calculation' => 'add',
    'shippingenabled' => null,
    'shippingbase' => null,
    'shippingitem' => null,
    'notificationemails' => '',
    'emailalerts' => '',
    'emailalertsname' => '',
    'guestCheckout' => 'off',
    'authnetLoginID' => '123456',
    'authnetTransactionKey' => '123456',
    'authnetTestmode' => '1',
    'invoiceMinimum' => '50',
    'invoiceMaximum' => '100',
    'paypalEmail' => 'nasir_roney@yahoo.com',
    'paypalTestMode' => '1',
    'paypalCurrency' => 'SGD',
    'fromCompanyName' => 'E-cart Services Malaysia Sdn Bhd 983365-K',
    'fromCompanyRegistrationNo' => '001947623424 (GST)',
    'fromCompanyFirstAddress' => 'Subang 1, Block B Lot 36545,',
    'fromCompanySecondAddress' => 'Jalan TS 6/1 Taman Perindustrian Subang,',
    'fromCompanyCountry' => 'MY',
    'fromCompanyCity' => 'Subang Jaya',
    'fromCompanyState' => 'Selangor',
    'fromCompanyPostal' => '47510',
    'paymentTimingDays' => '00',
    'paymentTimingHours' => '20',
    'paymentTimingMinutes' => '00',
    'paymentTimingSeconds' => '00',
);
